[package]
name = "advent_of_code_2015"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[profile.release]
opt-level = 3
debug = true

[profile.dev]
opt-level = 0
overflow-checks = true
